// <auto-generated />
using System;
using BooksEngine.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BooksEngine.Db.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260924145700_ModelExport")]
    partial class ModelExport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BooksEngine.Db.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_name");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("RatingsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ratings_count");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_authors_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.EaseWeight", b =>
                {
                    b.Property<int>("FromPos")
                        .HasColumnType("integer")
                        .HasColumnName("from_pos");

                    b.Property<int>("ToPos")
                        .HasColumnType("integer")
                        .HasColumnName("to_pos");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("FromPos", "ToPos")
                        .HasName("pk_ease_weights");

                    b.ToTable("ease_weights", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Edition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Asin")
                        .HasColumnType("text")
                        .HasColumnName("asin");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsEbook")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ebook");

                    b.Property<string>("Isbn")
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<string>("Isbn13")
                        .HasColumnType("text")
                        .HasColumnName("isbn13");

                    b.Property<string>("KindleAsin")
                        .HasColumnType("text")
                        .HasColumnName("kindle_asin");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<int?>("NumPages")
                        .HasColumnType("integer")
                        .HasColumnName("num_pages");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<long?>("RatingsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ratings_count");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TitleWithoutSeries")
                        .HasColumnType("text")
                        .HasColumnName("title_without_series");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("Isbn")
                        .HasDatabaseName("ix_editions_isbn");

                    b.HasIndex("Isbn13")
                        .HasDatabaseName("ix_editions_isbn13");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_editions_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_editions_work_id");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.ExternalId", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<long>("InternalId")
                        .HasColumnType("bigint")
                        .HasColumnName("internal_id");

                    b.HasKey("SourceId", "EntityType", "Value")
                        .HasName("pk_external_ids");

                    b.HasIndex("EntityType", "InternalId")
                        .HasDatabaseName("ix_external_ids_entity_type_internal_id");

                    b.ToTable("external_ids", null, t =>
                        {
                            t.HasCheckConstraint("ck_external_ids_entity_type", "entity_type IN ('work', 'edition', 'author')");
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.GoldenInput", b =>
                {
                    b.Property<string>("Profile")
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<bool>("Dnf")
                        .HasColumnType("boolean")
                        .HasColumnName("dnf");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.HasKey("Profile", "WorkId")
                        .HasName("pk_golden_inputs");

                    b.ToTable("golden_inputs", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.GoldenRecommendation", b =>
                {
                    b.Property<string>("Profile")
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.PrimitiveCollection<long[]>("Because")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("because");

                    b.Property<int>("Chance")
                        .HasColumnType("integer")
                        .HasColumnName("chance");

                    b.Property<long?>("Despite")
                        .HasColumnType("bigint")
                        .HasColumnName("despite");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.HasKey("Profile", "Rank")
                        .HasName("pk_golden_recommendations");

                    b.ToTable("golden_recommendations", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.ModelMeta", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.HasKey("Id")
                        .HasName("pk_model_meta");

                    b.ToTable("model_meta", null, t =>
                        {
                            t.HasCheckConstraint("ck_model_meta_single", "id = 1");
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Rating", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("UserId", "WorkId")
                        .HasName("pk_ratings");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_ratings_work_id");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_ratings_value", "value BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.ShelfEntry", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "WorkId")
                        .HasName("pk_shelves");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_shelves_work_id");

                    b.ToTable("shelves", null, t =>
                        {
                            t.HasCheckConstraint("ck_shelves_status", "status IN ('to_read', 'reading', 'read', 'dnf')");
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_code");

                    b.ToTable("sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "goodreads"
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.SourceLoad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Counts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("counts");

                    b.Property<DateTime>("LoadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest_sha256");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_source_loads");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_source_loads_source_id");

                    b.ToTable("source_loads", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Work", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BestEditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("best_edition_id");

                    b.Property<double?>("CfMeanRating")
                        .HasColumnType("double precision")
                        .HasColumnName("cf_mean_rating");

                    b.Property<int>("CfRatings")
                        .HasColumnType("integer")
                        .HasColumnName("cf_ratings");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("GrRatingsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("gr_ratings_count");

                    b.Property<long?>("GrRatingsSum")
                        .HasColumnType("bigint")
                        .HasColumnName("gr_ratings_sum");

                    b.Property<bool>("InCf")
                        .HasColumnType("boolean")
                        .HasColumnName("in_cf");

                    b.Property<bool>("IsCollection")
                        .HasColumnType("boolean")
                        .HasColumnName("is_collection");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("BestEditionId")
                        .HasDatabaseName("ix_works_best_edition_id");

                    b.HasIndex("OriginalTitle")
                        .HasDatabaseName("ix_works_original_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OriginalTitle"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("OriginalTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_works_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkAuthor", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("WorkId", "AuthorId")
                        .HasName("pk_work_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_work_authors_author_id");

                    b.ToTable("work_authors", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkCover", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("WorkId")
                        .HasName("pk_work_covers");

                    b.ToTable("work_covers", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkEmbedding", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<int>("Col")
                        .HasColumnType("integer")
                        .HasColumnName("col");

                    b.Property<int?>("EasePos")
                        .HasColumnType("integer")
                        .HasColumnName("ease_pos");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.HasKey("WorkId")
                        .HasName("pk_work_embeddings");

                    b.HasIndex("Col")
                        .IsUnique()
                        .HasDatabaseName("ix_work_embeddings_col");

                    b.HasIndex("EasePos")
                        .IsUnique()
                        .HasDatabaseName("ix_work_embeddings_ease_pos");

                    b.ToTable("work_embeddings", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkExclusion", b =>
                {
                    b.Property<long>("RatedWorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("rated_work_id");

                    b.Property<long>("ExcludedWorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("excluded_work_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("RatedWorkId", "ExcludedWorkId")
                        .HasName("pk_work_exclusions");

                    b.HasIndex("ExcludedWorkId")
                        .HasDatabaseName("ix_work_exclusions_excluded_work_id");

                    b.ToTable("work_exclusions", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_exclusions_reason", "reason IN ('series', 'rated')");
                        });
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkGenre", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<double>("Share")
                        .HasColumnType("double precision")
                        .HasColumnName("share");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("WorkId", "GenreId")
                        .HasName("pk_work_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_work_genres_genre_id");

                    b.ToTable("work_genres", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkMerge", b =>
                {
                    b.Property<string>("ShadowExternalId")
                        .HasColumnType("text")
                        .HasColumnName("shadow_external_id");

                    b.Property<long>("MainWorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("main_work_id");

                    b.HasKey("ShadowExternalId")
                        .HasName("pk_work_merges");

                    b.HasIndex("MainWorkId")
                        .HasDatabaseName("ix_work_merges_main_work_id");

                    b.ToTable("work_merges", (string)null);
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Edition", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Work", "Work")
                        .WithMany("Editions")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editions_works_work_id");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.ExternalId", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_ids_sources_source_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Rating", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_app_users_user_id");

                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.ShelfEntry", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shelves_app_users_user_id");

                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shelves_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.SourceLoad", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_loads_sources_source_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Work", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Edition", "BestEdition")
                        .WithMany()
                        .HasForeignKey("BestEditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_works_editions_best_edition_id");

                    b.Navigation("BestEdition");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkAuthor", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_authors_authors_author_id");

                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_authors_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkCover", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_covers_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkEmbedding", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_embeddings_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkExclusion", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("ExcludedWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_exclusions_works_excluded_work_id");

                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("RatedWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_exclusions_works_rated_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkGenre", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_genres_genres_genre_id");

                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_genres_works_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.WorkMerge", b =>
                {
                    b.HasOne("BooksEngine.Db.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("MainWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_merges_works_main_work_id");
                });

            modelBuilder.Entity("BooksEngine.Db.Entities.Work", b =>
                {
                    b.Navigation("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
